import { JobDetail } from "@/components/job-detail"
import { getJobs } from "@/lib/jobs-data"

// Placeholder data for job listings (should ideally come from an API or database)
const jobListings = [
  {
    id: "1",
    title: "Software Engineer",
    company: "TechNova Pvt. Ltd.",
    location: "Bangalore, Remote",
    salary: "₹6–8 LPA",
    postedDate: "23 Sept 2025",
    jobType: "Full-Time",
    shortDescription: "Looking for a full-stack developer with React + Node.js…",
    applyLink: "#",
    fullDescription:
      "We are seeking a highly motivated and skilled Software Engineer to join our dynamic team. You will be responsible for developing and maintaining web applications using React and Node.js, ensuring high performance and responsiveness. This role involves collaborating with cross-functional teams, participating in code reviews, and contributing to all phases of the development lifecycle.",
    requiredSkills: ["React", "Node.js", "JavaScript", "TypeScript", "SQL", "AWS"],
    experienceLevel: "3-5 years",
    educationRequirement: "B.Tech/B.E. in Computer Science or related field",
    perksBenefits: ["Health Insurance", "Remote Work", "Flexible Hours", "Learning & Development"],
    applicationDeadline: "31 Oct 2025",
    hrRecruiterContact: { name: "Alice Smith", email: "alice.smith@example.com" },
  },
  {
    id: "2",
    title: "Marketing Intern",
    company: "Global Corp",
    location: "New York",
    salary: "$60k–75k",
    postedDate: "22 Sept 2025",
    jobType: "Internship",
    shortDescription: "Seeking a creative marketing intern to assist with campaigns.",
    applyLink: "#",
    fullDescription:
      "Join our marketing team as an intern and gain hands-on experience in various marketing activities. You will assist with social media campaigns, content creation, market research, and event planning. This is a great opportunity to learn about digital marketing strategies and contribute to real-world projects.",
    requiredSkills: ["Social Media", "Content Creation", "Market Research", "Communication"],
    experienceLevel: "0-1 year",
    educationRequirement: "Currently pursuing a Bachelor's degree in Marketing or related field",
    perksBenefits: ["Mentorship Program", "Flexible Schedule", "Networking Events"],
    applicationDeadline: "15 Oct 2025",
    hrRecruiterContact: { name: "Bob Johnson", email: "bob.johnson@example.com" },
  },
  {
    id: "3",
    title: "Data Scientist",
    company: "Data Insights",
    location: "Remote",
    salary: "$100k–120k",
    postedDate: "21 Sept 2025",
    jobType: "Full-Time",
    shortDescription: "Experienced data scientist for advanced analytics projects.",
    applyLink: "#",
    fullDescription:
      "We are looking for an experienced Data Scientist to join our team and lead advanced analytics projects. You will be responsible for collecting, analyzing, and interpreting large datasets, building predictive models, and communicating insights to stakeholders. Strong programming skills in Python and experience with machine learning frameworks are essential.",
    requiredSkills: ["Python", "R", "Machine Learning", "SQL", "Data Visualization"],
    experienceLevel: "5+ years",
    educationRequirement: "Master's or Ph.D. in Data Science, Statistics, or Computer Science",
    perksBenefits: ["Remote Work", "Professional Development", "Performance Bonus"],
    applicationDeadline: "10 Nov 2025",
    hrRecruiterContact: { name: "Charlie Brown", email: "charlie.brown@example.com" },
  },
  {
    id: "4",
    title: "UX Designer",
    company: "Design Studio",
    location: "San Francisco",
    salary: "$80k–95k",
    postedDate: "20 Sept 2025",
    jobType: "Full-Time",
    shortDescription: "Passionate UX designer to create intuitive user experiences.",
    applyLink: "#",
    fullDescription:
      "We are seeking a passionate UX Designer to join our creative team. You will be responsible for conducting user research, creating wireframes and prototypes, and designing intuitive and engaging user experiences for our web and mobile applications. A strong portfolio demonstrating your design process and problem-solving skills is required.",
    requiredSkills: ["Figma", "Sketch", "User Research", "Wireframing", "Prototyping"],
    experienceLevel: "2-4 years",
    educationRequirement: "Bachelor's degree in Design, HCI, or related field",
    perksBenefits: ["Creative Environment", "Health & Wellness", "Paid Time Off"],
    applicationDeadline: "25 Oct 2025",
    hrRecruiterContact: { name: "Diana Prince", email: "diana.prince@example.com" },
  },
  {
    id: "5",
    title: "Product Manager",
    company: "Innovate Inc.",
    location: "London",
    salary: "£70k–90k",
    postedDate: "19 Sept 2025",
    jobType: "Full-Time",
    shortDescription: "Lead product development for our next-gen platform.",
    applyLink: "#",
    fullDescription:
      "We are looking for an experienced Product Manager to lead the development of our next-generation platform. You will define product strategy, gather requirements, prioritize features, and work closely with engineering, design, and marketing teams to deliver innovative products. Strong leadership and communication skills are essential.",
    requiredSkills: ["Product Strategy", "Roadmapping", "Agile Methodologies", "Market Analysis"],
    experienceLevel: "5+ years",
    educationRequirement: "Bachelor's degree in Business, Engineering, or related field; MBA preferred",
    perksBenefits: ["Performance Bonus", "Stock Options", "Travel Opportunities"],
    applicationDeadline: "05 Nov 2025",
    hrRecruiterContact: { name: "Eve Adams", email: "eve.adams@example.com" },
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "Cloud Solutions",
    location: "Remote",
    salary: "$90k–110k",
    postedDate: "18 Sept 2025",
    jobType: "Full-Time",
    shortDescription: "Build and maintain scalable infrastructure.",
    applyLink: "#",
    fullDescription:
      "Join our team as a DevOps Engineer and help us build and maintain scalable, reliable, and secure cloud infrastructure. You will be responsible for automating deployment processes, managing CI/CD pipelines, and ensuring the smooth operation of our systems. Experience with AWS, Docker, and Kubernetes is highly desirable.",
    requiredSkills: ["AWS", "Docker", "Kubernetes", "CI/CD", "Terraform"],
    experienceLevel: "3-5 years",
    educationRequirement: "Bachelor's degree in Computer Science or related field",
    perksBenefits: ["Remote Work", "Certification Reimbursement", "Flexible Hours"],
    applicationDeadline: "28 Oct 2025",
    hrRecruiterContact: { name: "Frank Green", email: "frank.green@example.com" },
  },
  {
    id: "7",
    title: "Content Writer",
    company: "Content Hub",
    location: "Mumbai",
    salary: "₹4–6 LPA",
    postedDate: "17 Sept 2025",
    jobType: "Contract",
    shortDescription: "Create engaging content for various platforms.",
    applyLink: "#",
    fullDescription:
      "We are looking for a talented Content Writer to create engaging and informative content for our website, blog, and social media channels. You will research industry-related topics, write clear marketing copy, and proofread articles before publication. Excellent writing and editing skills are a must.",
    requiredSkills: ["Content Writing", "SEO", "Editing", "Research", "Grammar"],
    experienceLevel: "1-3 years",
    educationRequirement: "Bachelor's degree in Journalism, Communications, or English",
    perksBenefits: ["Flexible Work", "Creative Freedom", "Professional Development"],
    applicationDeadline: "20 Oct 2025",
    hrRecruiterContact: { name: "Grace Hopper", email: "grace.hopper@example.com" },
  },
  {
    id: "8",
    title: "Sales Executive",
    company: "SalesForce",
    location: "Dallas",
    salary: "$50k–70k",
    postedDate: "16 Sept 2025",
    jobType: "Full-Time",
    shortDescription: "Drive sales and expand customer base.",
    applyLink: "#",
    fullDescription:
      "Join our dynamic sales team as a Sales Executive and drive revenue growth by identifying new business opportunities, building client relationships, and closing deals. You will be responsible for managing the entire sales cycle from lead generation to post-sales support. Proven sales experience and excellent negotiation skills are required.",
    requiredSkills: ["Sales", "Client Relationship Management", "Negotiation", "CRM Software"],
    experienceLevel: "2-5 years",
    educationRequirement: "Bachelor's degree in Business Administration or related field",
    perksBenefits: ["Commission Structure", "Health Benefits", "Car Allowance"],
    applicationDeadline: "18 Oct 2025",
    hrRecruiterContact: { name: "Harry Potter", email: "harry.potter@example.com" },
  },
  {
    id: "9",
    title: "HR Manager",
    company: "PeopleFirst",
    location: "Chicago",
    salary: "$70k–85k",
    postedDate: "15 Sept 2025",
    jobType: "Full-Time",
    shortDescription: "Manage human resources operations and talent acquisition.",
    applyLink: "#",
    fullDescription:
      "We are seeking an experienced HR Manager to oversee all aspects of human resources practices and processes. You will be responsible for talent acquisition, employee relations, performance management, and compliance with labor regulations. Strong leadership and interpersonal skills are essential for this role.",
    requiredSkills: ["HR Management", "Recruitment", "Employee Relations", "Labor Law", "HRIS"],
    experienceLevel: "5+ years",
    educationRequirement: "Bachelor's degree in Human Resources or Business Administration",
    perksBenefits: ["Comprehensive Benefits", "Professional Development", "Generous PTO"],
    applicationDeadline: "12 Oct 2025",
    hrRecruiterContact: { name: "Ivy Green", email: "ivy.green@example.com" },
  },
  {
    id: "10",
    title: "Graphic Designer",
    company: "Creative Minds",
    location: "Remote",
    salary: "$55k–70k",
    postedDate: "14 Sept 2025",
    jobType: "Full-Time",
    shortDescription: "Design visually appealing graphics for marketing materials.",
    applyLink: "#",
    fullDescription:
      "Join our creative team as a Graphic Designer and bring your artistic vision to life. You will be responsible for designing engaging visuals for marketing campaigns, websites, social media, and other brand materials. Proficiency in Adobe Creative Suite and a strong portfolio are required.",
    requiredSkills: ["Adobe Photoshop", "Adobe Illustrator", "Figma", "Typography", "Branding"],
    experienceLevel: "2-4 years",
    educationRequirement: "Bachelor's degree in Graphic Design or related field",
    perksBenefits: ["Creative Freedom", "Remote Work", "Flexible Hours"],
    applicationDeadline: "08 Oct 2025",
    hrRecruiterContact: { name: "Jack White", email: "jack.white@example.com" },
  },
]

export default function JobDetailPage({ params }: { params: { id: string } }) {
  const allJobs = getJobs(60)
  const job = allJobs.find((j) => j.id === params.id)

  if (!job) {
    return <div className="container mx-auto px-4 py-8 text-center text-red-500">Job not found.</div>
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <JobDetail {...job} />
    </div>
  )
}
